components:
    schemas:
        Channel:
            properties:
                channelId:
                    type: string
                createDate:
                    format: date
                    type: string
                dataSources:
                    items:
                        $ref: "#/components/schemas/DataSource"
                    type: array
                name:
                    type: string
        CommerceChannel:
            properties:
                channelName:
                    type: string
                id:
                    format: int64
                    type: integer
                name:
                    type: string
                siteName:
                    type: string
        ContactAccountGroup:
            properties:
                id:
                    format: int64
                    type: integer
                name:
                    type: string
                selected:
                    type: boolean
        ContactConfiguration:
            properties:
                syncAllAccounts:
                    type: boolean
                syncAllContacts:
                    type: boolean
                syncedAccountGroupIds:
                    items:
                        type: string
                    type: array
                syncedOrganizationIds:
                    items:
                        type: string
                    type: array
                syncedUserGroupIds:
                    items:
                        type: string
                    type: array
        ContactOrganization:
            properties:
                id:
                    format: int64
                    type: integer
                name:
                    type: string
                selected:
                    type: boolean
        ContactUserGroup:
            properties:
                id:
                    format: int64
                    type: integer
                name:
                    type: string
                selected:
                    type: boolean
        DataSource:
            properties:
                commerceChannelIds:
                    items:
                        format: int64
                        type: integer
                    type: array
                dataSourceId:
                    type: string
                siteIds:
                    items:
                        format: int64
                        type: integer
                    type: array
        DataSourceToken:
            properties:
                token:
                    type: string
        Site:
            properties:
                channelName:
                    type: string
                friendlyURL:
                    type: string
                id:
                    format: int64
                    type: integer
                name:
                    type: string
info:
    license:
        name: "Apache 2.0"
        url: "http://www.apache.org/licenses/LICENSE-2.0.html"
    title: ""
    version: v1.0
openapi: 3.0.1
paths:
    "/channels":
        get:
            operationId: getChannelsPage
            parameters:
                - in: query
                  name: keywords
                  schema:
                      type: string
                - in: query
                  name: filter
                  schema:
                      type: string
                - in: query
                  name: page
                  schema:
                      type: integer
                - in: query
                  name: pageSize
                  schema:
                      type: integer
            responses:
                200:
                    content:
                        application/json:
                            schema:
                                items:
                                    $ref: "#/components/schemas/Channel"
                                type: array
                        application/xml:
                            schema:
                                items:
                                    $ref: "#/components/schemas/Channel"
                                type: array
            tags: ["Channel"]
        patch:
            operationId: patchChannel
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/Channel"
                    application/xml:
                        schema:
                            $ref: "#/components/schemas/Channel"
            responses:
                200:
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Channel"
                        application/xml:
                            schema:
                                $ref: "#/components/schemas/Channel"
                    descritpion:
                        Patch Channel
                500:
                    content:
                        application/json:
                            schema:
                            type: string
                        application/xml:
                            schema:
                            type: string
                    description:
                        Unexpected error
            tags: ["Channel"]
        post:
            operationId: postChannel
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/Channel"
                    application/xml:
                        schema:
                            $ref: "#/components/schemas/Channel"
            responses:
                200:
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Channel"
                        application/xml:
                            schema:
                                $ref: "#/components/schemas/Channel"
                    descritpion:
                        Post New Channel
                500:
                    content:
                        application/json:
                            schema:
                            type: string
                        application/xml:
                            schema:
                            type: string
                    description:
                        Unexpected error
            tags: ["Channel"]
    "/commerce-channels":
        get:
            operationId: getCommerceChannelsPage
            parameters:
                - in: query
                  name: page
                  schema:
                      type: integer
                - in: query
                  name: pageSize
                  schema:
                      type: integer
            responses:
                200:
                    content:
                        application/json:
                            schema:
                                items:
                                    $ref: "#/components/schemas/CommerceChannel"
                                type: array
                        application/xml:
                            schema:
                                items:
                                    $ref: "#/components/schemas/CommerceChannel"
                                type: array
            tags: ["CommerceChannel"]
    "/contacts/account-groups":
        get:
            operationId: getContactAccountGroupsPage
            parameters:
                - in: query
                  name: keywords
                  schema:
                      type: string
                - in: query
                  name: page
                  schema:
                      type: integer
                - in: query
                  name: pageSize
                  schema:
                      type: integer
                - in: query
                  name: sort
                  schema:
                      type: string
            responses:
                200:
                    content:
                        application/json:
                            schema:
                                items:
                                    $ref: "#/components/schemas/ContactAccountGroup"
                                type: array
                        application/xml:
                            schema:
                                items:
                                    $ref: "#/components/schemas/ContactAccountGroup"
                                type: array
            tags: ["ContactAccountGroup"]
    "/contacts/configuration":
        get:
            operationId: getContactConfiguration
            responses:
                200:
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/ContactConfiguration"
                        application/xml:
                            schema:
                                $ref: "#/components/schemas/ContactConfiguration"
            tags: ["ContactConfiguration"]
        put:
            operationId: putContactConfiguration
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/ContactConfiguration"
                    application/xml:
                        schema:
                            $ref: "#/components/schemas/ContactConfiguration"
            responses:
                204:
                    content:
                        application/json: {}
                        application/xml: {}
            tags: ["ContactConfiguration"]
    "/contacts/organizations":
        get:
            operationId: getContactOrganizationsPage
            parameters:
                - in: query
                  name: keywords
                  schema:
                      type: string
                - in: query
                  name: page
                  schema:
                      type: integer
                - in: query
                  name: pageSize
                  schema:
                      type: integer
                - in: query
                  name: sort
                  schema:
                      type: string
            responses:
                200:
                    content:
                        application/json:
                            schema:
                                items:
                                    $ref: "#/components/schemas/ContactOrganization"
                                type: array
                        application/xml:
                            schema:
                                items:
                                    $ref: "#/components/schemas/ContactOrganization"
                                type: array
            tags: ["ContactOrganization"]
    "/contacts/user-groups":
        get:
            operationId: getContactUserGroupsPage
            parameters:
                - in: query
                  name: keywords
                  schema:
                      type: string
                - in: query
                  name: page
                  schema:
                      type: integer
                - in: query
                  name: pageSize
                  schema:
                      type: integer
                - in: query
                  name: sort
                  schema:
                      type: string
            responses:
                200:
                    content:
                        application/json:
                            schema:
                                items:
                                    $ref: "#/components/schemas/ContactUserGroup"
                                type: array
                        application/xml:
                            schema:
                                items:
                                    $ref: "#/components/schemas/ContactUserGroup"
                                type: array
            tags: ["ContactUserGroup"]
    "/data-sources":
        delete:
            operationId: deleteDataSource
            responses:
                204:
                    content:
                        application/json: {}
                        application/xml: {}
                    descritpion:
                        Disconnected
                500:
                    content:
                        application/json:
                            schema:
                            type: string
                        application/xml:
                            schema:
                            type: string
                    description:
                        Unexpected error
            tags: ["DataSource"]
        post:
            operationId: postDataSource
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/DataSourceToken"
                    application/xml:
                        schema:
                            $ref: "#/components/schemas/DataSourceToken"
            responses:
                204:
                    content:
                        application/json: {}
                        application/xml: {}
                    descritpion:
                        Connected
                500:
                    content:
                        application/json:
                            schema:
                            type: string
                        application/xml:
                            schema:
                            type: string
                    description:
                        Unexpected error
            tags: ["DataSource"]
    "/sites":
        get:
            operationId: getSitesPage
            parameters:
                - in: query
                  name: page
                  schema:
                      type: integer
                - in: query
                  name: pageSize
                  schema:
                      type: integer
            responses:
                200:
                    content:
                        application/json:
                            schema:
                                items:
                                    $ref: "#/components/schemas/Site"
                                type: array
                        application/xml:
                            schema:
                                items:
                                    $ref: "#/components/schemas/Site"
                                type: array
            tags: ["Site"]