info:
    description: "HeadlessUserNotification REST API"
    license:
        name: "Apache 2.0"
        url: "http://www.apache.org/licenses/LICENSE-2.0.html"
    title: "HeadlessUserNotification"
    version: v1.0
openapi: 3.0.1