apiDir: "../headless-user-notification-api/src/main/java"
apiPackagePath: "com.liferay.headless.user.notification"
application:
    baseURI: "/headless-user-notification"
    className: "HeadlessUserNotificationApplication"
    name: "Liferay.Headless.User.Notification"
author: "Carlos Correa"
clientDir: "../headless-user-notification-client/src/main/java"
forcePredictableOperationId: true
testDir: "../headless-user-notification-test/src/testIntegration/java"