components:
    schemas:
        NotificationQueueEntry:
            properties:
                actions:
                    additionalProperties:
                        additionalProperties:
                            type: string
                        type: object
                    readOnly: true
                    type: object
                body:
                    type: string
                fromName:
                    type: string
                id:
                    format: int64
                    readOnly: true
                    type: integer
                priority:
                    format: double
                    minimum: 0
                    type: number
                recipientsSummary:
                    readOnly: true
                    type: string
                sentDate:
                    format: date
                    readOnly: true
                    type: string
                status:
                    format: int32
                    type: integer
                subject:
                    type: string
                triggerBy:
                    type: string
                type:
                    readOnly: true
                    type: string
                typeLabel:
                    readOnly: true
                    type: string
            type: object
        NotificationTemplate:
            properties:
                actions:
                    additionalProperties:
                        additionalProperties:
                            type: string
                        type: object
                    readOnly: true
                    type: object
                attachmentObjectFieldIds:
                    items:
                        format: int64
                        type: integer
                    type: array
                body:
                    additionalProperties:
                        type: string
                    type: object
                dateCreated:
                    format: date
                    readOnly: true
                    type: string
                dateModified:
                    format: date
                    readOnly: true
                    type: string
                description:
                    type: string
                editorType:
                    enum: [freeMarker, richText]
                    type: string
                externalReferenceCode:
                    type: string
                id:
                    format: int64
                    readOnly: true
                    type: integer
                name:
                    type: string
                name_i18n:
                    additionalProperties:
                        type: string
                    type: object
                objectDefinitionId:
                    format: int64
                    type: integer
                recipientType:
                    type: string
                recipients:
                    items:
                        type: object
                    type: array
                subject:
                    additionalProperties:
                        type: string
                    type: object
                type:
                    type: string
                typeLabel:
                    type: string
            type: object
info:
    description:
        "A Java client JAR is available for use with the group ID 'com.liferay', artifact ID
        'com.liferay.notification.rest.client', and version '1.0.13'."
    license:
        name: "Apache 2.0"
        url: "http://www.apache.org/licenses/LICENSE-2.0.html"
    title: ""
    version: v1.0
openapi: 3.0.1
paths:
    "/notification-queue-entries":
        get:
            operationId: getNotificationQueueEntriesPage
            parameters:
                - in: query
                  name: filter
                  schema:
                      type: string
                - in: query
                  name: page
                  schema:
                      type: integer
                - in: query
                  name: pageSize
                  schema:
                      type: integer
                - in: query
                  name: search
                  schema:
                      type: string
                - in: query
                  name: sort
                  schema:
                      type: string
                - in: header
                  name: Accept-Language
                  schema:
                      type: string
            responses:
                200:
                    content:
                        application/json:
                            schema:
                                items:
                                    $ref: "#/components/schemas/NotificationQueueEntry"
                                type: array
                        application/xml:
                            schema:
                                items:
                                    $ref: "#/components/schemas/NotificationQueueEntry"
                                type: array
            tags: ["NotificationQueueEntry"]
    "/notification-queue-entries/{notificationQueueEntryId}":
        delete:
            operationId: deleteNotificationQueueEntry
            parameters:
                - in: path
                  name: notificationQueueEntryId
                  required: true
                  schema:
                      format: int64
                      type: integer
            responses:
                204:
                    content:
                        application/json: {}
                        application/xml: {}
            tags: ["NotificationQueueEntry"]
        get:
            operationId: getNotificationQueueEntry
            parameters:
                - in: path
                  name: notificationQueueEntryId
                  required: true
                  schema:
                      format: int64
                      type: integer
            responses:
                200:
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/NotificationQueueEntry"
                        application/xml:
                            schema:
                                $ref: "#/components/schemas/NotificationQueueEntry"
            tags: ["NotificationQueueEntry"]
    "/notification-queue-entries/{notificationQueueEntryId}/resend":
        put:
            operationId: putNotificationQueueEntryResend
            parameters:
                - in: path
                  name: notificationQueueEntryId
                  required: true
                  schema:
                      format: int64
                      type: integer
            responses:
                200:
                    content:
                        application/json: {}
                        application/xml: {}
            tags: ["NotificationQueueEntry"]
    "/notification-templates":
        get:
            operationId: getNotificationTemplatesPage
            parameters:
                - in: query
                  name: aggregationTerms
                  schema:
                      items:
                          type: string
                      type: array
                - in: query
                  name: filter
                  schema:
                      type: string
                - in: query
                  name: page
                  schema:
                      type: integer
                - in: query
                  name: pageSize
                  schema:
                      type: integer
                - in: query
                  name: search
                  schema:
                      type: string
                - in: query
                  name: sort
                  schema:
                      type: string
                - in: header
                  name: Accept-Language
                  schema:
                      type: string
            responses:
                200:
                    content:
                        application/json:
                            schema:
                                items:
                                    $ref: "#/components/schemas/NotificationTemplate"
                                type: array
                        application/xml:
                            schema:
                                items:
                                    $ref: "#/components/schemas/NotificationTemplate"
                                type: array
            tags: ["NotificationTemplate"]
        post:
            operationId: postNotificationTemplate
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/NotificationTemplate"
                    application/xml:
                        schema:
                            $ref: "#/components/schemas/NotificationTemplate"
            responses:
                200:
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/NotificationTemplate"
                        application/xml:
                            schema:
                                $ref: "#/components/schemas/NotificationTemplate"
            tags: ["NotificationTemplate"]
    "/notification-templates/by-external-reference-code/{externalReferenceCode}":
        get:
            operationId: getNotificationTemplateByExternalReferenceCode
            parameters:
                - in: path
                  name: externalReferenceCode
                  required: true
                  schema:
                      type: string
            responses:
                200:
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/NotificationTemplate"
                        application/xml:
                            schema:
                                $ref: "#/components/schemas/NotificationTemplate"
            tags: ["NotificationTemplate"]
        put:
            operationId: putNotificationTemplateByExternalReferenceCode
            parameters:
                - in: path
                  name: externalReferenceCode
                  required: true
                  schema:
                      type: string
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/NotificationTemplate"
                    application/xml:
                        schema:
                            $ref: "#/components/schemas/NotificationTemplate"
            responses:
                200:
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/NotificationTemplate"
                        application/xml:
                            schema:
                                $ref: "#/components/schemas/NotificationTemplate"
            tags: ["NotificationTemplate"]
    "/notification-templates/{notificationTemplateId}":
        delete:
            operationId: deleteNotificationTemplate
            parameters:
                - in: path
                  name: notificationTemplateId
                  required: true
                  schema:
                      format: int64
                      type: integer
            responses:
                204:
                    content:
                        application/json: {}
                        application/xml: {}
            tags: ["NotificationTemplate"]
        get:
            operationId: getNotificationTemplate
            parameters:
                - in: path
                  name: notificationTemplateId
                  required: true
                  schema:
                      format: int64
                      type: integer
            responses:
                200:
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/NotificationTemplate"
                        application/xml:
                            schema:
                                $ref: "#/components/schemas/NotificationTemplate"
            tags: ["NotificationTemplate"]
        patch:
            operationId: patchNotificationTemplate
            parameters:
                - in: path
                  name: notificationTemplateId
                  required: true
                  schema:
                      format: int64
                      type: integer
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/NotificationTemplate"
                    application/xml:
                        schema:
                            $ref: "#/components/schemas/NotificationTemplate"
            responses:
                200:
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/NotificationTemplate"
                        application/xml:
                            schema:
                                $ref: "#/components/schemas/NotificationTemplate"
            tags: ["NotificationTemplate"]
        put:
            operationId: putNotificationTemplate
            parameters:
                - in: path
                  name: notificationTemplateId
                  required: true
                  schema:
                      format: int64
                      type: integer
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/NotificationTemplate"
                    application/xml:
                        schema:
                            $ref: "#/components/schemas/NotificationTemplate"
            responses:
                200:
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/NotificationTemplate"
                        application/xml:
                            schema:
                                $ref: "#/components/schemas/NotificationTemplate"
            tags: ["NotificationTemplate"]
    "/notification-templates/{notificationTemplateId}/copy":
        post:
            operationId: postNotificationTemplateCopy
            parameters:
                - in: path
                  name: notificationTemplateId
                  required: true
                  schema:
                      format: int64
                      type: integer
            responses:
                200:
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/NotificationTemplate"
                        application/xml:
                            schema:
                                $ref: "#/components/schemas/NotificationTemplate"
            tags: ["NotificationTemplate"]